// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: socketmodel.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Model
{

    [global::ProtoBuf.ProtoContract(Name = @"basemsg")]
    public partial class Basemsg
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"msgcode")]
        public int Msgcode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"buff")]
        public byte[] Buff { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GChatContent
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"content")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Contents { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GChatData
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int ChatType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long SendDate { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"Content")]
        public global::System.Collections.Generic.List<byte[]> Contents { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(4)]
        public long FromUserID { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromNick { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public int FromExp { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string operID { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8)]
        public byte[] operParams { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"icon")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Icon { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"border")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Border { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11)]
        public int operType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BPlayerData
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
        public long Pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"picon")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Picon { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"piconborder")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Piconborder { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"pexp")]
        public int Pexp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"porganid")]
        public int Porganid { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021
