// Code generated by "stringer -type=MsgCodeType"; DO NOT EDIT.

package main

import "strconv"

const (
	_MsgCodeType_name_0 = "msgCodeLoginmsgCodeLoginRET"
	_MsgCodeType_name_1 = "msgCodePlayermsgCodePlayerRET"
)

var (
	_MsgCodeType_index_0 = [...]uint8{0, 12, 27}
	_MsgCodeType_index_1 = [...]uint8{0, 13, 29}
)

func (i MsgCodeType) String() string {
	switch {
	case 101 <= i && i <= 102:
		i -= 101
		return _MsgCodeType_name_0[_MsgCodeType_index_0[i]:_MsgCodeType_index_0[i+1]]
	case 1101 <= i && i <= 1102:
		i -= 1101
		return _MsgCodeType_name_1[_MsgCodeType_index_1[i]:_MsgCodeType_index_1[i+1]]
	default:
		return "MsgCodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
