// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameProto.proto

/*
Package gameProto is a generated protocol buffer package.

It is generated from these files:
	gameProto.proto

It has these top-level messages:
	ErrorMsgS2C
	AgainConnectC2S
	AgainConnectS2C
	OtherLoginS2C
	ConnectSuccessS2C
	Person
	UserLoginC2S
	UserLoginS2C
	GetUserInfoC2S
	GetUserInfoS2C
*/
package gameProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 错误消息
type ErrorMsgS2C struct {
	ErrorID          *int32 `protobuf:"varint,1,req,name=ErrorID" json:"ErrorID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ErrorMsgS2C) Reset()                    { *m = ErrorMsgS2C{} }
func (m *ErrorMsgS2C) String() string            { return proto.CompactTextString(m) }
func (*ErrorMsgS2C) ProtoMessage()               {}
func (*ErrorMsgS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorMsgS2C) GetErrorID() int32 {
	if m != nil && m.ErrorID != nil {
		return *m.ErrorID
	}
	return 0
}

// 重新连接C2S
type AgainConnectC2S struct {
	SessionID        *uint64 `protobuf:"varint,1,req,name=SessionID" json:"SessionID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AgainConnectC2S) Reset()                    { *m = AgainConnectC2S{} }
func (m *AgainConnectC2S) String() string            { return proto.CompactTextString(m) }
func (*AgainConnectC2S) ProtoMessage()               {}
func (*AgainConnectC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AgainConnectC2S) GetSessionID() uint64 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

// 重新连接S2C
type AgainConnectS2C struct {
	SessionID        *uint64 `protobuf:"varint,1,req,name=SessionID" json:"SessionID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AgainConnectS2C) Reset()                    { *m = AgainConnectS2C{} }
func (m *AgainConnectS2C) String() string            { return proto.CompactTextString(m) }
func (*AgainConnectS2C) ProtoMessage()               {}
func (*AgainConnectS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AgainConnectS2C) GetSessionID() uint64 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

// 其他客户端登录S2C
type OtherLoginS2C struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *OtherLoginS2C) Reset()                    { *m = OtherLoginS2C{} }
func (m *OtherLoginS2C) String() string            { return proto.CompactTextString(m) }
func (*OtherLoginS2C) ProtoMessage()               {}
func (*OtherLoginS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 连接成功S2C
type ConnectSuccessS2C struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ConnectSuccessS2C) Reset()                    { *m = ConnectSuccessS2C{} }
func (m *ConnectSuccessS2C) String() string            { return proto.CompactTextString(m) }
func (*ConnectSuccessS2C) ProtoMessage()               {}
func (*ConnectSuccessS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 用户数据
type Person struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	Money            *int32  `protobuf:"varint,3,req,name=Money" json:"Money,omitempty"`
	SessionID        *uint64 `protobuf:"varint,4,req,name=SessionID" json:"SessionID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Person) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetMoney() int32 {
	if m != nil && m.Money != nil {
		return *m.Money
	}
	return 0
}

func (m *Person) GetSessionID() uint64 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

// 用户登录C2S
type UserLoginC2S struct {
	UserName         *string `protobuf:"bytes,1,req,name=UserName" json:"UserName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserLoginC2S) Reset()                    { *m = UserLoginC2S{} }
func (m *UserLoginC2S) String() string            { return proto.CompactTextString(m) }
func (*UserLoginC2S) ProtoMessage()               {}
func (*UserLoginC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UserLoginC2S) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

// 用户登录S2C
type UserLoginS2C struct {
	UserID           *uint64 `protobuf:"varint,1,req,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserLoginS2C) Reset()                    { *m = UserLoginS2C{} }
func (m *UserLoginS2C) String() string            { return proto.CompactTextString(m) }
func (*UserLoginS2C) ProtoMessage()               {}
func (*UserLoginS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserLoginS2C) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 获取用户信息C2S
type GetUserInfoC2S struct {
	UserID           *uint64 `protobuf:"varint,1,req,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetUserInfoC2S) Reset()                    { *m = GetUserInfoC2S{} }
func (m *GetUserInfoC2S) String() string            { return proto.CompactTextString(m) }
func (*GetUserInfoC2S) ProtoMessage()               {}
func (*GetUserInfoC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetUserInfoC2S) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 获取用户信息S2C
type GetUserInfoS2C struct {
	UserInfo         *Person `protobuf:"bytes,1,req,name=UserInfo" json:"UserInfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetUserInfoS2C) Reset()                    { *m = GetUserInfoS2C{} }
func (m *GetUserInfoS2C) String() string            { return proto.CompactTextString(m) }
func (*GetUserInfoS2C) ProtoMessage()               {}
func (*GetUserInfoS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetUserInfoS2C) GetUserInfo() *Person {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorMsgS2C)(nil), "ErrorMsgS2C")
	proto.RegisterType((*AgainConnectC2S)(nil), "AgainConnectC2S")
	proto.RegisterType((*AgainConnectS2C)(nil), "AgainConnectS2C")
	proto.RegisterType((*OtherLoginS2C)(nil), "OtherLoginS2C")
	proto.RegisterType((*ConnectSuccessS2C)(nil), "ConnectSuccessS2C")
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterType((*UserLoginC2S)(nil), "UserLoginC2S")
	proto.RegisterType((*UserLoginS2C)(nil), "UserLoginS2C")
	proto.RegisterType((*GetUserInfoC2S)(nil), "GetUserInfoC2S")
	proto.RegisterType((*GetUserInfoS2C)(nil), "GetUserInfoS2C")
}

func init() { proto.RegisterFile("gameProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xe9, 0x9a, 0xb6, 0x76, 0xaa, 0x0d, 0xae, 0x22, 0x41, 0x3c, 0x94, 0x15, 0x34, 0x78,
	0xa8, 0x10, 0xf0, 0x07, 0x48, 0x2a, 0x52, 0xb0, 0x5a, 0x12, 0xbc, 0x1b, 0xc2, 0x18, 0x73, 0xe8,
	0x8e, 0xec, 0xc6, 0x83, 0xff, 0x5e, 0x66, 0x93, 0xae, 0xb6, 0xa0, 0x97, 0x90, 0x6f, 0xf6, 0xcd,
	0xdb, 0xf7, 0x16, 0xc2, 0xaa, 0x58, 0xe3, 0xca, 0x50, 0x43, 0xb3, 0x0f, 0xfe, 0xaa, 0x2b, 0x18,
	0xdf, 0x1b, 0x43, 0x66, 0x69, 0xab, 0x3c, 0x49, 0x65, 0x04, 0x43, 0x87, 0x8b, 0x79, 0xd4, 0x9b,
	0x8a, 0xb8, 0x9f, 0x6d, 0x50, 0xdd, 0x40, 0x78, 0x57, 0x15, 0xb5, 0x4e, 0x49, 0x6b, 0x2c, 0x9b,
	0x34, 0xc9, 0xe5, 0x39, 0x8c, 0x72, 0xb4, 0xb6, 0x26, 0xdd, 0xc9, 0x83, 0xec, 0x67, 0xb0, 0xbb,
	0xc0, 0xee, 0xff, 0x2f, 0x84, 0x70, 0xf8, 0xdc, 0xbc, 0xa3, 0x79, 0xa4, 0xaa, 0xd6, 0x79, 0x92,
	0xaa, 0x63, 0x38, 0xda, 0x2c, 0x7f, 0x96, 0x25, 0x5a, 0xcb, 0xc3, 0x57, 0x18, 0xac, 0xd0, 0x58,
	0xd2, 0x72, 0x02, 0xc2, 0xdb, 0x88, 0xc5, 0x5c, 0x4a, 0x08, 0x9e, 0x8a, 0x35, 0x46, 0x62, 0x2a,
	0xe2, 0x51, 0xe6, 0xfe, 0xe5, 0x09, 0xf4, 0x97, 0xa4, 0xf1, 0x2b, 0xda, 0x73, 0x6d, 0x5a, 0xd8,
	0xce, 0x11, 0xec, 0xe6, 0xb8, 0x86, 0x83, 0x17, 0xdb, 0xc5, 0xe0, 0x9a, 0x67, 0xb0, 0xcf, 0xec,
	0xbc, 0x7b, 0xce, 0xdb, 0xb3, 0xba, 0xfc, 0xa5, 0xe5, 0x86, 0xa7, 0x30, 0x60, 0xf6, 0xb9, 0x3a,
	0x52, 0x31, 0x4c, 0x1e, 0xb0, 0x71, 0xa0, 0xdf, 0x88, 0x5d, 0xff, 0x52, 0xde, 0x6e, 0x29, 0xd9,
	0xf3, 0xa2, 0xbd, 0x9f, 0xd1, 0x69, 0xc7, 0xc9, 0x70, 0xd6, 0x3e, 0x41, 0xe6, 0x0f, 0xbe, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0xfd, 0xd8, 0x11, 0xd9, 0x01, 0x00, 0x00,
}
